-- MySQL Script generated by MySQL Workbench
-- Tue Jul 26 01:11:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema heroku_223933ee5a0b633
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `heroku_223933ee5a0b633` ;

-- -----------------------------------------------------
-- Schema heroku_223933ee5a0b633
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `heroku_223933ee5a0b633` DEFAULT CHARACTER SET utf8 ;
USE `heroku_223933ee5a0b633` ;

-- -----------------------------------------------------
-- Table `heroku_223933ee5a0b633`.`perfilsystem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_223933ee5a0b633`.`perfilsystem` (
  `perfilsystem_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `perfilsystem_nombre` VARCHAR(15) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `perfilsystem_descripcion` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `perfilsystem_estado` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`perfilsystem_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `heroku_223933ee5a0b633`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_223933ee5a0b633`.`clientes` (
  `cliente_id` CHAR(5) CHARACTER SET 'utf8mb4' NOT NULL,
  `cliente_dni` VARCHAR(8) CHARACTER SET 'utf8mb4' NOT NULL,
  `cliente_nombre` VARCHAR(25) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `cliente_apellido` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `cliente_direccion` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `cliente_telefono` VARCHAR(9) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `cliente_email` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `cliente_fecha_registro` DATE NOT NULL,
  `cliente_usser` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `cliente_password` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `cliente_estado` TINYINT(1) NOT NULL,
  `cliente_perfil` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`cliente_id`),
  CONSTRAINT `clientes_cliente_perfil_foreign`
    FOREIGN KEY (`cliente_perfil`)
    REFERENCES `heroku_223933ee5a0b633`.`perfilsystem` (`perfilsystem_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `clientes_cliente_perfil_foreign` ON `heroku_223933ee5a0b633`.`clientes` (`cliente_perfil` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `heroku_223933ee5a0b633`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_223933ee5a0b633`.`empleados` (
  `empleado_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `empleado_dni` VARCHAR(8) CHARACTER SET 'utf8mb4' NOT NULL,
  `empleado_nombre` VARCHAR(25) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `empleado_apellido` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `empleado_direccion` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `empleado_telefono` VARCHAR(9) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `empleado_email` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `empleado_fecha_registro` DATE NOT NULL,
  `empleado_usser` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `empleado_password` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `empleado_estado` TINYINT(1) NOT NULL,
  `empleado_perfil` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`empleado_id`),
  CONSTRAINT `empleados_empleado_perfil_foreign`
    FOREIGN KEY (`empleado_perfil`)
    REFERENCES `heroku_223933ee5a0b633`.`perfilsystem` (`perfilsystem_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `empleados_empleado_perfil_foreign` ON `heroku_223933ee5a0b633`.`empleados` (`empleado_perfil` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `heroku_223933ee5a0b633`.`comprobantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_223933ee5a0b633`.`comprobantes` (
  `comprobante_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `comprobante_tipo` VARCHAR(15) CHARACTER SET 'utf8mb4' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`comprobante_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `heroku_223933ee5a0b633`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_223933ee5a0b633`.`ventas` (
  `venta_id` CHAR(5) CHARACTER SET 'utf8mb4' NOT NULL,
  `venta_fecha_emitida` DATE NOT NULL,
  `venta_hora_emitida` TIME NOT NULL,
  `venta_igv` CHAR(5) CHARACTER SET 'utf8mb4' NOT NULL,
  `venta_cliente` CHAR(5) CHARACTER SET 'utf8mb4' NOT NULL,
  `venta_empleado` BIGINT(20) UNSIGNED NOT NULL,
  `venta_tipo_comprobante` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`venta_id`),
  CONSTRAINT `ventas_venta_cliente_foreign`
    FOREIGN KEY (`venta_cliente`)
    REFERENCES `heroku_223933ee5a0b633`.`clientes` (`cliente_id`)
    ON DELETE CASCADE,
  CONSTRAINT `ventas_venta_empleado_foreign`
    FOREIGN KEY (`venta_empleado`)
    REFERENCES `heroku_223933ee5a0b633`.`empleados` (`empleado_id`)
    ON DELETE CASCADE,
  CONSTRAINT `ventas_venta_tipo_comprobante_foreign`
    FOREIGN KEY (`venta_tipo_comprobante`)
    REFERENCES `heroku_223933ee5a0b633`.`comprobantes` (`comprobante_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `ventas_venta_cliente_foreign` ON `heroku_223933ee5a0b633`.`ventas` (`venta_cliente` ASC) VISIBLE;

CREATE INDEX `ventas_venta_empleado_foreign` ON `heroku_223933ee5a0b633`.`ventas` (`venta_empleado` ASC) VISIBLE;

CREATE INDEX `ventas_venta_tipo_comprobante_foreign` ON `heroku_223933ee5a0b633`.`ventas` (`venta_tipo_comprobante` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `heroku_223933ee5a0b633`.`boletas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_223933ee5a0b633`.`boletas` (
  `boleta_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `boleta_venta` CHAR(5) CHARACTER SET 'utf8mb4' NOT NULL,
  `boleta_total` DECIMAL(10,2) NOT NULL,
  `tipo_comprobante` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`boleta_id`),
  CONSTRAINT `boletas_boleta_venta_foreign`
    FOREIGN KEY (`boleta_venta`)
    REFERENCES `heroku_223933ee5a0b633`.`ventas` (`venta_id`)
    ON DELETE CASCADE,
  CONSTRAINT `boletas_tipo_comprobante_foreign`
    FOREIGN KEY (`tipo_comprobante`)
    REFERENCES `heroku_223933ee5a0b633`.`comprobantes` (`comprobante_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `boletas_boleta_venta_foreign` ON `heroku_223933ee5a0b633`.`boletas` (`boleta_venta` ASC) VISIBLE;

CREATE INDEX `boletas_tipo_comprobante_foreign` ON `heroku_223933ee5a0b633`.`boletas` (`tipo_comprobante` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `heroku_223933ee5a0b633`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_223933ee5a0b633`.`categorias` (
  `categoria_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `categoria_nombre` VARCHAR(35) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `categoria_imagen` VARCHAR(30) CHARACTER SET 'utf8mb4' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`categoria_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 54
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `heroku_223933ee5a0b633`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_223933ee5a0b633`.`productos` (
  `producto_id` CHAR(5) CHARACTER SET 'utf8mb4' NOT NULL,
  `producto_nombre` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `producto_descripcion` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `producto_categoria` BIGINT(20) UNSIGNED NOT NULL,
  `producto_precio_compra` DECIMAL(10,2) NOT NULL,
  `producto_precio_venta` DECIMAL(10,2) NOT NULL,
  `producto_stock` INT(11) NOT NULL,
  `producto_fecha_registro` DATE NOT NULL,
  `producto_imagen` VARCHAR(30) CHARACTER SET 'utf8mb4' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`producto_id`),
  CONSTRAINT `productos_producto_categoria_foreign`
    FOREIGN KEY (`producto_categoria`)
    REFERENCES `heroku_223933ee5a0b633`.`categorias` (`categoria_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `productos_producto_categoria_foreign` ON `heroku_223933ee5a0b633`.`productos` (`producto_categoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `heroku_223933ee5a0b633`.`detalleventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_223933ee5a0b633`.`detalleventas` (
  `detalleventa_venta` CHAR(5) CHARACTER SET 'utf8mb4' NOT NULL,
  `detalleventa_producto` CHAR(5) CHARACTER SET 'utf8mb4' NOT NULL,
  `detalleventa_cantidad` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  CONSTRAINT `detalleventas_detalleventa_producto_foreign`
    FOREIGN KEY (`detalleventa_producto`)
    REFERENCES `heroku_223933ee5a0b633`.`productos` (`producto_id`)
    ON DELETE CASCADE,
  CONSTRAINT `detalleventas_detalleventa_venta_foreign`
    FOREIGN KEY (`detalleventa_venta`)
    REFERENCES `heroku_223933ee5a0b633`.`ventas` (`venta_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `detalleventas_detalleventa_venta_foreign` ON `heroku_223933ee5a0b633`.`detalleventas` (`detalleventa_venta` ASC) VISIBLE;

CREATE INDEX `detalleventas_detalleventa_producto_foreign` ON `heroku_223933ee5a0b633`.`detalleventas` (`detalleventa_producto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `heroku_223933ee5a0b633`.`facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_223933ee5a0b633`.`facturas` (
  `factura_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `factura_venta` CHAR(5) CHARACTER SET 'utf8mb4' NOT NULL,
  `factura_subtotal` DECIMAL(10,2) NOT NULL,
  `factura_igv` DECIMAL(10,2) NOT NULL,
  `factura_total` DECIMAL(10,2) NOT NULL,
  `tipo_comprobante` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`factura_id`),
  CONSTRAINT `facturas_factura_venta_foreign`
    FOREIGN KEY (`factura_venta`)
    REFERENCES `heroku_223933ee5a0b633`.`ventas` (`venta_id`)
    ON DELETE CASCADE,
  CONSTRAINT `facturas_tipo_comprobante_foreign`
    FOREIGN KEY (`tipo_comprobante`)
    REFERENCES `heroku_223933ee5a0b633`.`comprobantes` (`comprobante_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `facturas_factura_venta_foreign` ON `heroku_223933ee5a0b633`.`facturas` (`factura_venta` ASC) VISIBLE;

CREATE INDEX `facturas_tipo_comprobante_foreign` ON `heroku_223933ee5a0b633`.`facturas` (`tipo_comprobante` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `heroku_223933ee5a0b633`.`libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_223933ee5a0b633`.`libros` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(250) NOT NULL,
  `imagen` VARCHAR(2500) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `heroku_223933ee5a0b633`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_223933ee5a0b633`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 224
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

USE `heroku_223933ee5a0b633` ;

-- -----------------------------------------------------
-- procedure myStoredProcedure_ObtenerVentasPorMes
-- -----------------------------------------------------

DELIMITER $$
USE `heroku_223933ee5a0b633`$$
CREATE DEFINER=`be49acc7cd9fec`@`%` PROCEDURE `myStoredProcedure_ObtenerVentasPorMes`(IN `AN` INT)
SELECT MONTH(F.venta_fecha_emitida) MES, COUNT(*) CANTIDAD, SUM(A.producto_precio_venta *D.detalleventa_cantidad) TOTAL
FROM ventas F, detalleventas D, productos A
WHERE F.venta_id=D.detalleventa_venta AND D.detalleventa_producto=A.producto_id
AND YEAR(F.venta_fecha_emitida)=AN
GROUP BY MONTH(F.venta_fecha_emitida)$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure myStoredProcedure_grabarCliente
-- -----------------------------------------------------

DELIMITER $$
USE `heroku_223933ee5a0b633`$$
CREATE DEFINER=`be49acc7cd9fec`@`%` PROCEDURE `myStoredProcedure_grabarCliente`(DNI VARCHAR(8),NOMBRES VARCHAR(25),APELLIDOS VARCHAR(30),DIRECCION VARCHAR(45),TELEFONO VARCHAR(9),CORREOELECTRONICO VARCHAR(30),FECHAREGISTRO DATE,USUARIO VARCHAR(30),CONTRASENA VARCHAR(30),ESTADO TINYINT(1),PERFILSISTEMA_IDPERFILSISTEMA BIGINT(20),CREATEDAT TIMESTAMP,UPDATEDAT TIMESTAMP)
BEGIN
DECLARE CUENTA INT;
DECLARE CODCLI CHAR(5);
SELECT right(MAX(cliente_id),4)+1 INTO CUENTA FROM CLIENTES;
SET CODCLI=CONCAT('C',LPAD(CUENTA,4,'0'));
INSERT INTO CLIENTES(cliente_id,cliente_dni,cliente_nombre,cliente_apellido,cliente_direccion,cliente_telefono,cliente_email,cliente_fecha_registro,cliente_usser,cliente_password,cliente_estado,cliente_perfil,created_at,updated_at) VALUES(CODCLI,DNI,NOMBRES,APELLIDOS,DIRECCION,TELEFONO,CORREOELECTRONICO,FECHAREGISTRO,USUARIO,CONTRASENA,ESTADO,PERFILSISTEMA_IDPERFILSISTEMA,CREATEDAT,UPDATEDAT);
select CODCLI;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure myStoredProcedure_grabarDetalleVenta
-- -----------------------------------------------------

DELIMITER $$
USE `heroku_223933ee5a0b633`$$
CREATE DEFINER=`be49acc7cd9fec`@`%` PROCEDURE `myStoredProcedure_grabarDetalleVenta`(CODVENTA CHAR(5),CODPRODUCTO CHAR(5),CANTIDAD INT(11),CREATEDAT TIMESTAMP, UPDATEDAT TIMESTAMP)
BEGIN
INSERT INTO detalleventas (detalleventa_venta,detalleventa_producto,detalleventa_cantidad,created_at,updated_at)  VALUES(CODVENTA,CODPRODUCTO,CANTIDAD,CREATEDAT,UPDATEDAT);
UPDATE productos SET productos.producto_stock=productos.producto_stock-CANTIDAD WHERE productos.producto_id=CODPRODUCTO;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure myStoredProcedure_grabarEmpleado
-- -----------------------------------------------------

DELIMITER $$
USE `heroku_223933ee5a0b633`$$
CREATE DEFINER=`be49acc7cd9fec`@`%` PROCEDURE `myStoredProcedure_grabarEmpleado`(IN `DNI` VARCHAR(8), IN `NOMBRES` VARCHAR(25), IN `APELLIDOS` VARCHAR(30), IN `DIRECCION` VARCHAR(45), IN `TELEFONO` VARCHAR(9), IN `CORREOELECTRONICO` VARCHAR(30), IN `FECHAREGISTRO` DATE, IN `USUARIO` VARCHAR(30), IN `CONTRASENA` VARCHAR(30), IN `ESTADO` TINYINT(1), IN `PERFILSISTEMA_IDPERFILSISTEMA` BIGINT(20), IN `CREATEDAT` TIMESTAMP, IN `UPDATEDAT` TIMESTAMP)
BEGIN
DECLARE CUENTA INT;
DECLARE CODCLI CHAR(5);
SELECT right(MAX(empleado_id),4)+1 INTO CUENTA FROM EMPLEADOS;
SET CODCLI=CONCAT('E',LPAD(CUENTA,4,'0'));
INSERT INTO EMPLEADOS(empleado_id,empleado_dni,empleado_nombre,empleado_apellido,empleado_direccion,empleado_telefono,empleado_email,empleado_fecha_registro,empleado_usser,empleado_password,empleado_estado,empleado_perfil,created_at,updated_at) VALUES(CODCLI,DNI,NOMBRES,APELLIDOS,DIRECCION,TELEFONO,CORREOELECTRONICO,FECHAREGISTRO,USUARIO,CONTRASENA,ESTADO,PERFILSISTEMA_IDPERFILSISTEMA,CREATEDAT,UPDATEDAT);
select CODCLI;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure myStoredProcedure_grabarProducto
-- -----------------------------------------------------

DELIMITER $$
USE `heroku_223933ee5a0b633`$$
CREATE DEFINER=`be49acc7cd9fec`@`%` PROCEDURE `myStoredProcedure_grabarProducto`(IN `NOMBRE` VARCHAR(30), IN `DESCRIPCION` VARCHAR(100), IN `CATEGORIA` BIGINT(20), IN `PRECIOCOMPRA` DECIMAL(10,2), IN `PRECIOVENTA` DECIMAL(10,2), IN `STOCK` INT(11), IN `FECHAREGISTRO` DATE, IN `IMAGEN` VARCHAR(30), IN `CREATEDAT` TIMESTAMP, IN `UPDATEDAT` TIMESTAMP)
BEGIN
DECLARE CUENTA INT;
DECLARE CODPRO CHAR(5);
SELECT right(MAX(producto_id),4)+1 INTO CUENTA FROM PRODUCTOS;
SET CODPRO=CONCAT('A',LPAD(CUENTA,4,'0'));
INSERT INTO PRODUCTOS (producto_id,producto_nombre,producto_descripcion,producto_categoria,producto_precio_compra,producto_precio_venta,producto_stock,producto_fecha_registro,producto_imagen,created_at,updated_at) VALUES (CODPRO,NOMBRE,DESCRIPCION,CATEGORIA,PRECIOCOMPRA,PRECIOVENTA,STOCK,FECHAREGISTRO,IMAGEN,CREATEDAT,UPDATEDAT);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure myStoredProcedure_grabarVenta
-- -----------------------------------------------------

DELIMITER $$
USE `heroku_223933ee5a0b633`$$
CREATE DEFINER=`be49acc7cd9fec`@`%` PROCEDURE `myStoredProcedure_grabarVenta`(IN `codcli` CHAR(5), IN `fec` DATE, IN `hor` TIME, IN `figv` CHAR(5), IN `codvend` BIGINT(20), IN `tcomprob` BIGINT(20), IN `createdat` TIMESTAMP, IN `updatedat` TIMESTAMP)
begin
declare cuenta int;
declare fac char(5);
select right(max(venta_id),4)+1 into cuenta from ventas;
set fac=concat('F',Lpad(cuenta,4,'0'));
insert into ventas (venta_id,venta_fecha_emitida,venta_hora_emitida,venta_igv,venta_cliente,venta_empleado,venta_tipo_comprobante,created_at,updated_at) values(fac,fec,hor,figv,codcli,codvend,tcomprob,createdat,updatedat);
select fac;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
